### ISSUE TITLE
"go get" fails to get

### ISSUE THREAD

**Issue by Bu11etmagnet** [google/codesearch#42]
`$ go get code.google.com/p/codesearch/cmd/...`
`package code.google.com/p/codesearch/cmd/...: unable to detect version control system for code.google.com/ path`

Oh well, let's try github:

`$ go get github.com/google/codesearch/...`
`package github.com/google/codesearch/...`
`	imports github.com/google/codesearch/cmd/cgrep`
`	imports code.google.com/p/codesearch/regexp: unable to detect version control system for code.google.com/ path`
`package github.com/google/codesearch/...`
`	imports github.com/google/codesearch/cmd/cindex`
`	imports code.google.com/p/codesearch/index: unable to detect version control system for code.google.com/ path`
`package github.com/google/codesearch/...`
`	imports github.com/google/codesearch/index`
`	imports code.google.com/p/codesearch/sparse: unable to detect version control system for code.google.com/ path`

**Comment by dgryski** [comment]
This will be fixed when https://github.com/google/codesearch/pull/39 is merged.

**Comment by zavislak** [comment]
Line 15 of `cmd/csearch/csearch.go` still points to code.google.com/p/codesearch
