### ISSUE TITLE
Where are the binaries?

### ISSUE THREAD

**Issue by jamesblackshaw** [google/codesearch#52]
I've looked in here and although the top-level readme references binaries I can't find anything that isn't a .go file.

**Comment by dgryski** [comment]
The README contains information that is outdated from when it was hosted on code.google.com.  Binaries must be built from source.  Install a Go compiler and then run

`go get github.com/google/codesearch/cmd/{csearch,cindex}`

**Comment by frederich** [comment]
Damian, the README should be update (a45d81b686e85d01f2838439deaf72126ccd5a96).

**Comment by dgryski** [comment]
The README was updated to mention the move from code.google.com, but not the new lack of provided binaries.  Precompiled binaries are currently not available.

**Comment by frederich** [comment]
Agreed!

**Comment by suntong** [comment]
The README, which says, 

> Binary downloads are available for those who do not have Go installed.
> See https://github.com/google/codesearch.

should really be corrected. 

BTW, I bet most of those people seeking binary downloads are Windows people. 
I myself is looking for Windows binary just to save me doing compiling myself on that pathetic platform.

**Comment by junkblocker** [comment]
If you are ok with a fork with some changes, you can get binaries from https://github.com/junkblocker/codesearch/releases .

**Comment by suntong** [comment]
"*A fork ... to  make it a more generally usable tool*"
I like it! 
and thanks too for the precompiled binaries for Windows, that pathetic platform I hate doing compiling on my own.
