### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by enefry** [google/codesearch#58]
I want to source my android source like https://cs.chromium.org/
But  after i 
install golang-go  
install codesearch  
and run "go get github.com/google/codesearch/cmd/{cindex,csearch}"

 cindex  xxxSourcesxxx/

I don't know to make a website like  https://cs.chromium.org/ to search android source 
Is there any step-by-step guidance ?

I index android sources by openGrok before .
Is there any guidance  like this 
https://github.com/OpenGrok/OpenGrok/blob/master/README.txt

**Comment by rsc** [comment]
This is just a command-line tool, not a web site. For a web site maybe try https://codeascraft.com/2015/01/27/announcing-hound-a-lightning-fast-code-search-tool/.
